#!/bin/bash

# Variables
BUCKET_NAME="ds2022-xqd7aq"
FILE_PATH="google-logo.jpg"
AWS_REGION="us-east-1"       

# Upload the file to the specified S3 bucket
aws s3 cp "$FILE_PATH" "s3://$BUCKET_NAME/" --region "$AWS_REGION"

# Extract the file name from the file path
FILE_NAME=$(basename "$FILE_PATH")

# Generate a presigned URL valid for 7 days (604800 seconds)
echo "Generating presigned URL..."
PRESIGNED_URL=$(aws s3 presign "s3://$BUCKET_NAME/$FILE_NAME" --expires-in 604800 --region "$AWS_REGION")

# Output the presigned URL
echo "Presigned URL: $PRESIGNED_URL"

# Save the presigned URL to the script for submission
echo "# Presigned URL generated by the script:" >> lab4.sh
echo "# $PRESIGNED_URL" >> lab4.sh

# Presigned URL generated by the script:
# https://ds2022-xqd7aq.s3.us-east-1.amazonaws.com/google-logo.jpg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA4SYAMKKOM3ZSAKQX%2F20241001%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241001T234953Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=b7bf1ecf861509b906ea94fb5e400b4009c1cfb15f5a0ef86b679d2d705ff40a
